- .eslintrc.js
- .gitignore
- next.config.js
- package.json
- pages/404.tsx
- pages/index.tsx
- pages/map.tsx
- pages/mypage.tsx
- pages/wish.tsx
- server/server.js
- tsconfig.json
- utils/authentication/useUser.ts
- yarn.lock
JWT 설정 파일을 만들었습니다~
따로 코드 리뷰 세션 만들도록 하겠습니다~
- ⬜️ 리팩토링
> add jwt verify & login

- components/Organisms/Common/Container.tsx
- ⬜️ 리팩토링
- ✅ QA 및 버그 수정
conflit 에러 수정
> Fix: conflit error

- assets/error/Alert.tsx
- pages/404.tsx
- ⬜️ 리팩토링
- ✅화면 개발 ( 추가, 수정, 삭제 )
> Feat: error layout

- package.json
- server/server.js
- utils/authentication/useUser.ts
- utils/hooks/customAxios.ts
- yarn.lock
> proxy logic 생성

- components/Organisms/List/ListSection.tsx
> fix build error change recoil

- components/Atoms/Select.tsx
- components/Molecules/ModalHeader.tsx
- components/Molecules/Portal.tsx
- components/Organisms/Modal/Filter.tsx
- components/Organisms/Modal/ModalBox.tsx
- components/Organisms/Modal/ModalContainer.tsx
- components/Organisms/Modal/ModalLayout.tsx
- components/Organisms/Modal/Select.tsx
- constants/common.ts
- constants/type/initialModal.tsx
- constants/type/modal.ts
- pages/_app.tsx
- pages/_document.tsx
- pages/index.tsx
- states/modal.ts
- styles/theme/index.ts
- utils/hooks/useModal.tsx
- ⬜️ 리팩토링
Organisms-modal - select => 정렬 레이어 팝업
Organisms-modal - filter => 상세필터 레이어 팝업
-----
아래 코드는 modalType애 select를 주어 정렬 레이어 팝업을 정의
```
<Select
modalType="Select"
data={exampleSelect}
onChange={(e) => {
e.target.value;
}}
/>
```
아래 코드는 modalType애 Filter를 주어 상세필터 레이어 팝업을 정의
```
<Select
modalType="Filter"
data={exampleFilter}
onChange={(e) => {
e.target.value;
}}
/>
```
현재는 아래와 같이 select와 filter가 디자인 되어 있습니다.
상황에 맞게 다음 컴포넌트를 수정하시면 될 것 같습니다.
Organisms-modal - select => 정렬 레이어 팝업
Organisms-modal - filter => 상세필터 레이어 팝업
> Feat: modal id 생성

- pages/mypage.tsx
- server/server.js
> Feature: simple login

- components/Organisms/MyPage/Update/UpdateInputSet.tsx
> input change

- styles/index.css
> Fix: a/button color 수정

- components/Organisms/Common/HeaderBar.tsx
- ⬜️ 리팩토링
- ✅ QA 및 버그 수정
일부 기기에서 제대로 나오지 않았던 Flex를 수정하였습니다.
> fix: menubar align

- components/Organisms/Archive/Record.tsx
- states/detail.ts
- ⬜️ 리팩토링
- ✅ QA 및 버그 수정
사용하지 않는 console.log()를 삭제하였습니다.
> remove unused console log

- components/Molecules/TopTabView.tsx
- ⬜️ 리팩토링
- ⬜️  QA 및 버그 수정
SwipeableViews animation 효과 삭제
> Fix SwipeableViews animation효과 수정

- components/Atoms/Shadow.tsx
- components/Atoms/index.ts
- components/Molecules/Popup.tsx
- components/Organisms/Popup/AlertCancelConfirmPopup.tsx
- components/Organisms/Popup/AlertConfirmPopup.tsx
- components/Organisms/Popup/AlertSuccessPopup.tsx
- components/Organisms/Popup/PopupRouter.tsx
- constants/alertMessage.ts
- constants/popupName.ts
- pages/index.tsx
- states/alertState.ts
- states/index.ts
- states/popupName.ts
- ⬜️ 리팩토링
팝업창 예시 입니다.
1. constants > popupName.ts 
팝업창 상수 이름 설정
2. constants > alertMessage.ts 
팝업창 안의 메시지 정의 ) 노션 참고
https://kimseyoung.notion.site/ALERT-CONFIRM-060267ab7bd843dcbc7144f0f90d9be1
3. components > Organisms > Popup > ~~~.tsx 
팝업창에 띄울 컴포넌트 제작
ex) AlertConfirmPopup.tsx, AlertCancelConfirmPopup.tsx 참고
알림창 ) AlertConfirmPopup.tsx, AlertCancelConfirmPopup.tsx 사용
알림창 제외) return 에서 Popup컴포넌트 사용 => 쉐도우 부분이기 때문입니다!
4. components > Organisms > Popup > PopupRouter.tsx
case에 popupName.ts 에서 정의했던 이름 케이스로 3번에 제작한 컴포넌트 return 해서 보여주도록 하기
5.  pages > index.tsx 참고하여 사용하고자 하는 팝업창 띄우기
예시)
```tsx
const setPopupName = useSetRecoilState(PopupNameState);
...
<Button
onClick={() => {
setAlertState(ALERT_MESSAGE.ALERT.CANCEL_RECONFIRM); …
```
> popup창 띄우기

- components/Organisms/MyPage/Update/UpdateInputSet.tsx
- pages/_document.tsx
- ⬜️ 리팩토링
- ✅ QA 및 버그 수정
더이상 모바일에는 줌이 되지 않습니다.
date를 고를때에도 이제 제대로 white box로 보입니다.
> fix mobile issue

- components/Organisms/Modal/SearchMap.tsx
- ⬜️ 리팩토링
- ✅ QA 및 버그 수정
아카이브 기록하기 장소찾기 부분
- 엑스 누르면 입력한 내용 전체 삭제
- 돋보기 누르면 입력한 내용으로 검색 가능
> Refator: 아카이브 기록하기 장소찾기 돋보기 추가

- components/Organisms/Detail/Description.tsx
- components/Organisms/Detail/Description/Archive.tsx
- components/Organisms/Detail/ExhibitionImagesSection.tsx
> ERROR : 상세페이지 유료 가격 간격 8px 수정

- assets/mypage/Folder.tsx
- components/Molecules/TopTabView.tsx
- ⬜️ 리팩토링
- ✅화면 개발 ( 추가, 수정, 삭제 )
- ⬜️QA 및 버그 수정
- 그림자 없는 svg로 변경하고 그림자효과를 줄 수 있는 box를 따로 추가하였습니다.
> fix : 플로팅 버튼 svg 교체, 그림자 분리

- components/Molecules/AddressInput.tsx
- components/Organisms/Modal/SearchMap.tsx
- ⬜️ 리팩토링
- ✅ QA 및 버그 수정
1. 맛집
2. 카페
> Fix: 아카이브기록하기 다녀온장소찾기 팝업 타이틀 수정

- assets/list/ArrowDown.tsx
- components/Molecules/ModalHeader.tsx
- components/Organisms/List/ListOptionFilter.tsx
- components/Organisms/List/ListSortFilter.tsx
- components/Organisms/Modal/Filter/FilterSelect.tsx
- components/Organisms/Modal/Filter/index.tsx
- components/Organisms/Modal/ModalLayout.tsx
- components/Organisms/Modal/Select.tsx
- ⬜️ 리팩토링
- ✅ QA 및 버그 수정
1. 모달창 닫기 버튼 추가
2. 상세필터 버튼과 하단 간격 추가
3. 상세필터 2단 정렬 -> 3단 정렬
height를 제플린에 맞춰서 555px 고정값으로 잡았습니다
> 리스트 페이지 모달 팝업창 디자인 수정

- components/Organisms/MyPage/Archive/ListCard.tsx
- components/Organisms/Pick/PickCard.tsx
- ⬜️ 리팩토링
- ✅ QA 및 버그 수정
- 콘솔경고 없애기
- 슈도 클래스 nth-child, nth-last-child -> nth-of-type, nth-last-of-type 으로 변경
> 슈도클래스 n-th child console 경고 수정

- states/list.ts
- states/search-request.ts
- ⬜️ 리팩토링
- ✅ QA 및 버그 수정
- 카테고리 변경 또는 필터 적용 > 다른페이지 진입 > 뒤로가기
→ 리스트가 선택한 필터에 맞게 노출되지 않았던 이슈 수정
> 리스트데이터 초기화 수정

- assets/common/header/Search.tsx
- components/Organisms/Common/HeaderBar.tsx
- components/Organisms/Detail/Description.tsx
- components/Organisms/Detail/Description/Archive.tsx
- components/Organisms/Detail/Description/Summary.tsx
- components/Organisms/Detail/ExhibitionImagesSection.tsx
- components/Organisms/Detail/Navigator.tsx
- pages/detail/[id]/index.tsx
- states/detail.ts
- states/index.ts
* Fix: 홈페이지 바로가기 수정
* Fix: 안쓰는 함수 제거
* Refactor: 돋보기와 홈 아이콘 간격조절
* Refactor: 돋보기와 홈 아이콘 간격조절
* Feat: 아카이브 제목 추가
* Feat: 단순 아카이브 제목 추가
* Feat: 아카이브 스크롤 paddingtop 추가
* Refacotr: detail state 재정비 및 summary 파일 나누기
* Fix: 아카이브 새로고침
* Feat: 사진 아카이브만 눌렀을 때 사진 아카이브만 노출
- ⬜️ 리팩토링
- ✅ QA 및 버그 수정
> 상세페이지 관련 에러처리 (#121)

- components/Molecules/AddressInput.tsx
- components/Molecules/StarScope.tsx
- components/Organisms/Archive/ArchiveHome.tsx
- components/Organisms/Archive/Rating.tsx
- components/Organisms/Detail/Description.tsx
- components/Organisms/Detail/Description/Archive.tsx
- components/Organisms/Detail/Description/Summary.tsx
- components/Organisms/Detail/ExhibitionImagesSection.tsx
- components/Organisms/Detail/Navigator.tsx
- components/Organisms/Detail/NavigatorHeart.tsx
- pages/archive/update.tsx
- pages/detail/[id]/index.tsx
- states/archiveWirte.ts
- states/index.ts
> build error 수정

- components/Molecules/AddressInput.tsx
- components/Molecules/StarScope.tsx
- components/Organisms/Archive/ArchiveHome.tsx
- components/Organisms/Archive/Rating.tsx
- components/Organisms/Detail/Description.tsx
- components/Organisms/Detail/Description/Archive.tsx
- components/Organisms/Detail/Description/Summary.tsx
- components/Organisms/Detail/ExhibitionImagesSection.tsx
- components/Organisms/Detail/Navigator.tsx
- components/Organisms/Detail/NavigatorHeart.tsx
- pages/archive/update.tsx
- pages/detail/[id]/index.tsx
- states/archiveWirte.ts
- states/index.ts
* merge
* Fix: build error_state name, recoilloadable
* Refactor: 아카이브 수정하기 api 제거
* Refactor: 로그인 풀림
* Refactor: 콘솔 삭제
* Fix: 아카이브 사진만 보기에서 없을경우
- ⬜️ 리팩토링
- ✅ QA 및 버그 수정
> build error 수정 (#125)

- components/Organisms/Archive/ArchiveHome.tsx
- components/Organisms/Detail/Description/Summary.tsx
- components/Organisms/Detail/ExhibitionImagesSection.tsx
- components/Organisms/Detail/Navigator.tsx
- components/Organisms/Detail/NavigatorHeart.tsx
- pages/detail/[id]/index.tsx
- states/detail.ts
- ⬜️ 리팩토링
- ✅ QA 및 버그 수정
1. 아카이브 취소 클릭시 에러팝업 뜨는 이슈
=> 뒤로가기 적용 ( 상세페이지로 넘어감 )
2. 상세페이지에서 연속으로 하트 클릭 불가
=> state를 분리해 하트만 받아옴 ( list페에지에서 하트 클릭시 상세페이지에서도 적용)
> 상세페이지 하트픽에러, 아카이브 취소클릭시 에러

- components/Organisms/Archive/ArchiveHome.tsx
- components/Organisms/Detail/Description/Summary.tsx
- components/Organisms/Detail/ExhibitionImagesSection.tsx
- components/Organisms/Detail/Navigator.tsx
- components/Organisms/Detail/NavigatorHeart.tsx
- pages/detail/[id]/index.tsx
- states/detail.ts
* 아카이브 취소시 에러팝업 뜨는 것  수정
* Fix: 취소시 상세페이지로 이동
* 상세페이지에서 연속으로 하트클릭 불가 에러
* Refactor: 작업 분리
- ⬜️ 리팩토링
- ✅ QA 및 버그 수정
> 상세페이지 하트픽에러, 아카이브 취소클릭시 에러 (#127)

- components/Organisms/Archive/ArchiveFileUploadForm/InputArchiveSquare.tsx
- ⬜️ 리팩토링
- ✅ QA 및 버그 수정
+ 버튼보다 클릭되는 영역의 z인덱스를 더 높게 잡음
> 아카이브기록하기 이미지 추가 버튼 '+' 영역에서 안눌리는 이슈 수정

- components/Organisms/Archive/ArchiveFileUploadForm/InputArchiveSquare.tsx
> Refactor: 아카이브기록하기 이미지 추가 할 시  '+' 버튼 클릭 (#132)

- components/Organisms/Archive/ArchiveHome.tsx
- components/Organisms/Popup/AlertArchiveCancelConfirmPopup.tsx
- components/Organisms/Popup/PopupRouter.tsx
- constants/popupName.ts
> Feat: 아카이브 기록하기/수정하기 취소 컨펌

- components/Organisms/Archive/ArchiveHome.tsx
- components/Organisms/Popup/AlertArchiveCancelConfirmPopup.tsx
- components/Organisms/Popup/PopupRouter.tsx
- constants/popupName.ts
> Feat: 아카이브 기록하기/수정하기 취소 컨펌 (#135)

- components/Organisms/Detail/Description/ArchiveHeart.tsx
- states/archiveWirte.ts
> Feat: 아카이브 댓글 좋아요 api 추가

- components/Organisms/Search/PickRanking.tsx
- components/Organisms/Search/SwipeItem/SwipeItemImage.tsx
- components/Organisms/Search/SwipeItem/SwipeItemInfo.tsx
- components/Organisms/Search/SwipeItem/index.tsx
- components/Organisms/Search/data.ts
- pages/search/index.tsx
- states/index.ts
- states/pickRanking.ts
- ⬜️ 리팩토링
1. 더미 데이터로 많이 픽한 문화 생활 목업작업
> 많이 픽한 문화생활 목업

- components/Organisms/MyPage/Archive/Detail/MyArchiveDetailCardHeader.tsx
- components/Organisms/Popup/AlertArchiveDeletePopup.tsx
- ⬜️ 리팩토링
- ✅ QA 및 버그 수정
다시 올리는 #143  PR
> update: 마이아카이브 > 삭제 

- components/Organisms/MyPage/MyPageHome.tsx
- pages/mypage/index.tsx
- ⬜️ 리팩토링
- ✅ QA 및 버그 수정
- 마이페이지에서 비로그인 상태인데 my api 호출하는 현상 수정
> fix: 비로그인 상태인데 api 호출하는 문제

- components/Organisms/Archive/ArchiveTitle.tsx
- components/Organisms/Common/HeaderBar.tsx
- components/Organisms/Detail/Description/Archive.tsx
- pages/archive/index.tsx
- pages/archive/update.tsx
- ⬜️ 리팩토링
- ✅ QA 및 버그 수정
X버튼 수정
url 수정
| 기존화면 | 사진 아카이브 없을때 | 소개글 x, 아카이브o 일경우 사진만 보이기 |
| -------- | -------- | -------- |
| ![image](https://user-images.githubusercontent.com/48988891/206819196-a1780488-33da-45ac-9474-d1d98e0ade10.png) | ![image](https://user-images.githubusercontent.com/48988891/206819207-261cb4bf-f403-4d29-9566-4ab037b81b3f.png) | ![image](https://user-images.githubusercontent.com/48988891/206819218-3e8309d2-8f3e-442d-b4fe-56448d418b30.png)
> [상세페이지] 에러처리

- .gitignore
- components/Organisms/Home/Module/KeyVisual/InfinitiCarouselTitle.tsx
- components/Organisms/Home/Module/MonthlyFreeItem/MonthlyFreeItemCard.tsx
- components/Organisms/Home/Module/MonthlyFreeItem/index.tsx
- components/Organisms/Home/ModuleTypes.tsx
- pages/home-list.tsx
- states/home.ts
> fix: br 태그 삽입

- components/Organisms/MyPage/Archive/Detail/MyArchiveDetailCardInfo.tsx
- ⬜️ 리팩토링
- ⬜️QA 및 버그 수정
마이아카이브 디테일 팝업 > 별점 CSS 수정
> update: 마이아카이브 별점

- components/Organisms/MyPage/Archive/Detail/MyArchiveDetailCardInfo.tsx
- next.config.js
- ⬜️ 리팩토링
- ✅ QA 및 버그 수정
1. 마이아카이브 디테일 팝업 별점 CSS.
2.  히스토리 백 시, 스크롤 위치 저장.
> [Sprint 32-3] 마이아카이브 디테일 , 히스토리 백

- components/Organisms/Detail/Description/Summary.tsx
> [Fix] 티켓 url 입력시에만 보이기

- README.md
1. 많이 픽한 문화생활 타이틀 변경
2. 많이 픽한 문화생활 종료 텍스트 위치 변경
3. 홈 이달의 프리티켓 아이템에 이미지가 없을 시 noimage 처리
4. [Sprint 33] 관련 내용 재 배포
Co-authored-by: Kim Han Sol <48988891+kimhan0421@users.noreply.github.com>
> [Sprint 33-1] 많이픽한 문화생활, 홈 이달의 프리티켓  (#201) (#202)

- components/Organisms/ArchiveCreate/ArchiveCreateHome.tsx
- components/Organisms/ArchiveUpdate/ArchiveUpdateHome.tsx
- components/Organisms/MyPage/Update/UpdateButton.tsx
- states/detail.ts
- states/myArchiveList.ts
- utils/authentication/useUser.ts
| 기존화면 | 수정화면 |
| -------- | -------- |
| 화면캡쳐 | 화면캡쳐 |
> [hotfix] API Issue

- components/Organisms/Info/Introduce.tsx
> [Refactor] 킬로미터소개 > 팀원 추가

- components/Organisms/Home/Footer.tsx
홈 화면에서 로고 옆 부분을 드래그하면 현재 배포한 버전을 알 수 있음
| 기존화면 | 수정화면 |
| -------- | -------- |
| <img width="454" alt="image" src="https://user-images.githubusercontent.com/48988891/218258910-4a596ade-5d48-4d8e-b5a9-df908b86017a.png"> | <img width="336" alt="image" src="https://user-images.githubusercontent.com/48988891/218258902-a74e4319-5226-4318-9cff-b1c23084a983.png"> |
> [ Feat ] [홈] 버전추가

- package.json
| 기존화면 | 수정화면 |
| -------- | -------- |
| 화면캡쳐 | 화면캡쳐 |
> [VER] v1.34.2

- states/detail.ts
| 기존화면 | 수정화면 |
| -------- | -------- |
| 화면캡쳐 | 화면캡쳐 |
> [SPRINT33] fix api issue
